/*
 * KAMINGUYEN PORTFOLIO — EDITABLE CONTENT
 * ---------------------------------------------------------
 * This is the main file to edit when information changes.
 * Update text between quotes, prices, links, titles, or artwork
 * categories here. The layout and interactions live elsewhere.
 */

window.SITE_CONTENT = {
  profile: {
    name: "Kaminguyen",
    intro:
      "Character-led illustrations, expressive designs, and narrative art shaped with atmosphere and feeling.",
    bio:
      "I’m a freelance illustrator who loves expressive faces, cinematic light, and characters who feel alive before they say a word. My work moves between polished illustration, visual storytelling, and original character design.",
    basedIn: "Vietnam",
    languages: "VIE · ENG",
    age: "20+",
    experience: "Freelance illustrator",
    availability: "Opening in August",
    availabilityShort: "Open in August",
    slots: "Slots: 2 / 2",
    software: [
      "Procreate",
      "Medibang Paletta",
      "FlipaClip: Draw 2D Animation",
      "MediBang Paint",
      "Clip Studio Paint",
    ],
    skills: [
      "Character design",
      "Concept art",
      "Digital illustration",
      "Manga & sequential art",
    ],
  },

  contacts: [
    {
      id: "email",
      label: "Email",
      handle: "nguyenngoctram15082008@gmail.com",
      href: "mailto:nguyenngoctram15082008@gmail.com",
    },
    {
      id: "tiktok",
      label: "TikTok",
      handle: "@kn_nnt8",
      href: "https://www.tiktok.com/@kn_nnt8?_r=1&_t=ZS-98P85lAmrJd",
    },
    {
      id: "instagram",
      label: "Instagram",
      handle: "@tram.ng.kami",
      href: "https://www.instagram.com/tram.ng.kami?igsh=MTJ0YnJiZnFvZWJkYg==",
    },
    {
      id: "facebook",
      label: "Facebook",
      handle: "Kaminguyen",
      href: "https://www.facebook.com/share/1EQfER1yBB/?mibextid=wwXIfr",
    },
    {
      id: "zalo",
      label: "Zalo",
      handle: "0395 660 827 · +84 395 660 827",
      href: "https://zalo.me/84395660827",
    },
    {
      id: "imessage",
      label: "iMessage / Phone",
      handle: "+84 395 660 827",
      href: "sms:+84395660827",
    },
  ],

  payment: {
    label: "International payment",
    method: "PayPal.",
    holder: "Đức Anh Tô",
    for: "International commissions",
    note:
      "Scan the QR code in the PayPal app after your final quote has been confirmed. Please include your commission name or invoice reference.",
  },

  /*
   * Add future event cards to this array. Each item can use a local image
   * as its cover and link to a Drive folder, registration page, or recap.
   */
  events: [
    {
      title: "Kaminguyen Drawing Events",
      eyebrow: "Event archive · Google Drive",
      description:
        "Drawing challenges, community prompts, collaborations, and future event photos — collected in one growing archive.",
      cover: "assets/art/art-30.webp",
      coverAlt: "Kaminguyen drawing at a desk at night",
      href:
        "https://drive.google.com/drive/mobile/folders/1dCB0nbo1RYXQchN48pF26bGETfDQFYau?safe=active",
      linkLabel: "Open the event archive",
    },
  ],

  disciplines: [
    {
      id: "illustration",
      number: "01",
      title: "Illustration",
      description:
        "Polished, atmospheric images with character, light, and story at the center.",
    },
    {
      id: "comics",
      number: "02",
      title: "Manga & storytelling",
      description:
        "Sequential art, expressive panels, and visual pacing built around emotion.",
    },
    {
      id: "design",
      number: "03",
      title: "Character design",
      description:
        "Silhouettes, costumes, turnarounds, and visual identities made to be remembered.",
    },
  ],

  artworks: [
    {
      sourceIndex: 34,
      title: "Spring🌼",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-34.jpg",
      thumb: "assets/art/thumbs/art-34.jpg",
      width: 2560,
      height: 1828,
    },
    {
      sourceIndex: 1,
      title: "Golden Hour",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-01.webp",
      thumb: "assets/art/thumbs/art-01.webp",
      width: 1651,
      height: 2561,
    },
    {
      sourceIndex: 2,
      title: "Bunny Cadet",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-02.webp",
      thumb: "assets/art/thumbs/art-02.webp",
      width: 1290,
      height: 2266,
    },
    {
      sourceIndex: 4,
      title: "White Mask",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-04.webp",
      thumb: "assets/art/thumbs/art-04.webp",
      width: 1082,
      height: 1280,
    },
    {
      sourceIndex: 5,
      title: "Frostbound",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-05.webp",
      thumb: "assets/art/thumbs/art-05.webp",
      width: 1948,
      height: 2048,
    },
    {
      sourceIndex: 6,
      title: "Crimson Motion",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-06.webp",
      thumb: "assets/art/thumbs/art-06.webp",
      width: 1379,
      height: 2048,
    },
    {
      sourceIndex: 7,
      title: "Soft Study",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-07.webp",
      thumb: "assets/art/thumbs/art-07.webp",
      width: 1924,
      height: 2560,
    },
    {
      sourceIndex: 10,
      title: "The Night Drive",
      category: "comics",
      year: "2026",
      file: "assets/art/art-10.webp",
      thumb: "assets/art/thumbs/art-10.webp",
      width: 1280,
      height: 716,
    },
    {
      sourceIndex: 14,
      title: "A Quiet Bargain",
      category: "comics",
      year: "2026",
      file: "assets/art/art-14.webp",
      thumb: "assets/art/thumbs/art-14.webp",
      width: 1825,
      height: 2560,
    },
    {
      sourceIndex: 15,
      title: "Not So Calm",
      category: "comics",
      year: "2026",
      file: "assets/art/art-15.webp",
      thumb: "assets/art/thumbs/art-15.webp",
      width: 1825,
      height: 2560,
    },
    {
      sourceIndex: 16,
      title: "Courtside",
      category: "comics",
      year: "2026",
      file: "assets/art/art-16.webp",
      thumb: "assets/art/thumbs/art-16.webp",
      width: 1617,
      height: 2560,
    },
    {
      sourceIndex: 17,
      title: "After School",
      category: "comics",
      year: "2026",
      file: "assets/art/art-17.webp",
      thumb: "assets/art/thumbs/art-17.webp",
      width: 1296,
      height: 2560,
    },
    {
      sourceIndex: 18,
      title: "Three Beats",
      category: "comics",
      year: "2026",
      file: "assets/art/art-18.webp",
      thumb: "assets/art/thumbs/art-18.webp",
      width: 1667,
      height: 2560,
    },
    {
      sourceIndex: 19,
      title: "Not in the Mood",
      category: "comics",
      year: "2026",
      file: "assets/art/art-19.webp",
      thumb: "assets/art/thumbs/art-19.webp",
      width: 1993,
      height: 2560,
    },
    {
      sourceIndex: 20,
      title: "Already Missing You",
      category: "comics",
      year: "2026",
      file: "assets/art/art-20.webp",
      thumb: "assets/art/thumbs/art-20.webp",
      width: 945,
      height: 2560,
    },
    {
      sourceIndex: 21,
      title: "Blue Reverie",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-21.webp",
      thumb: "assets/art/thumbs/art-21.webp",
      width: 2003,
      height: 2560,
    },
    {
      sourceIndex: 22,
      title: "Red Hound",
      category: "design",
      year: "2026",
      file: "assets/art/art-22.webp",
      thumb: "assets/art/thumbs/art-22.webp",
      width: 2431,
      height: 2560,
    },
    {
      sourceIndex: 23,
      title: "Midnight Passenger",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-23.webp",
      thumb: "assets/art/thumbs/art-23.webp",
      width: 2560,
      height: 2275,
    },
    {
      sourceIndex: 24,
      title: "Runaway Waltz",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-24.webp",
      thumb: "assets/art/thumbs/art-24.webp",
      width: 2560,
      height: 2000,
    },
    {
      sourceIndex: 25,
      title: "Celestial Oracle",
      category: "design",
      year: "2026",
      file: "assets/art/art-25.webp",
      thumb: "assets/art/thumbs/art-25.webp",
      width: 2560,
      height: 1541,
    },
    {
      sourceIndex: 26,
      title: "Silver Guard",
      category: "design",
      year: "2026",
      file: "assets/art/art-26.webp",
      thumb: "assets/art/thumbs/art-26.webp",
      width: 2560,
      height: 2019,
    },
    {
      sourceIndex: 27,
      title: "Sunday Noir",
      category: "design",
      year: "2026",
      file: "assets/art/art-27.webp",
      thumb: "assets/art/thumbs/art-27.webp",
      width: 2394,
      height: 2560,
    },
    {
      sourceIndex: 28,
      title: "Blue Host",
      category: "design",
      year: "2026",
      file: "assets/art/art-28.webp",
      thumb: "assets/art/thumbs/art-28.webp",
      width: 1755,
      height: 2560,
    },
    {
      sourceIndex: 29,
      title: "Red Hound — Turnaround",
      category: "design",
      year: "2026",
      file: "assets/art/art-29.webp",
      thumb: "assets/art/thumbs/art-29.webp",
      width: 2560,
      height: 1707,
    },
    {
      sourceIndex: 30,
      title: "After Hours",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-30.webp",
      thumb: "assets/art/thumbs/art-30.webp",
      width: 2000,
      height: 1580,
    },
    {
      sourceIndex: 31,
      title: "A Spark at Midnight",
      category: "illustration",
      year: "2026",
      file: "assets/art/art-31.webp",
      thumb: "assets/art/thumbs/art-31.webp",
      width: 2000,
      height: 1580,
    },
  ],

  pricing: {
    standard: [
      { type: "Bust up", usd: "$75", vnd: "2.0m VND" },
      { type: "Half body", usd: "$100", vnd: "2.7m VND" },
      { type: "Knee up", usd: "$120", vnd: "3.2m VND" },
      { type: "Full body", usd: "$150", vnd: "4.0m VND" },
      { type: "Illustration", usd: "$300", vnd: "8.0m VND" },
    ],
    cartoon: [
      { type: "Bust up", usd: "$30", vnd: "0.8m VND" },
      { type: "Half body", usd: "$50", vnd: "1.4m VND" },
      { type: "Knee up", usd: "Quote", vnd: "Liên hệ" },
      { type: "Full body", usd: "Quote", vnd: "Liên hệ" },
      { type: "Illustration", usd: "$200", vnd: "5.4m VND" },
    ],
    addons: [
      "Detailed character design: +$10–30",
      "Complex background: +$10–100",
      "Props: +$5–15",
      "Additional character: +100% of total price",
      "Monetized content / promotion: +100%",
      "Commercial merchandising / reproduction / selling: +200%",
    ],
    note:
      "VND estimates use a high bank selling rate of 26,510 VND/USD and are always rounded up to the next 0.1m VND. ETA: 1–3 months. Bust-up and chibi commissions may take around 2 weeks. Add-on prices are estimates and may change depending on complexity.",
  },

  process: [
    {
      number: "01",
      title: "Brief & references",
      text: "Send the character, pose, colors, lighting, deadline, and intended use.",
    },
    {
      number: "02",
      title: "Quote & payment",
      text: "A final quote is confirmed. Full payment is required upfront via PayPal.",
    },
    {
      number: "03",
      title: "Sketch",
      text: "Initial and final sketches are shared for approval before color begins.",
    },
    {
      number: "04",
      title: "Color & rendering",
      text: "Base color, color sketch, and rendering are approved stage by stage.",
    },
    {
      number: "05",
      title: "Delivery",
      text: "Final PNG files are delivered through Google Drive.",
    },
  ],

  terms: [
    {
      roman: "I",
      title: "General disclaimer",
      items: [
        "By placing a commission, you agree to these Terms of Service.",
        "I reserve the right to decline or cancel any commission for any reason. Refunds are handled according to the refund policy below.",
        "All commissions are digital only.",
        "Disrespectful or inappropriate behaviour will result in commission cancellation.",
      ],
    },
    {
      roman: "II",
      title: "User agreement",
      items: [
        "The artwork is for personal, non-profit use only, unless commercial rights are purchased.",
        "Proper credit must be given when posting the artwork.",
        "Violation of these terms may result in being blacklisted from future commissions.",
        "Both the Client and the Artist agree not to share private messages or personal/contact information with third parties without mutual consent.",
      ],
    },
    {
      roman: "III",
      title: "Client responsibility",
      items: [
        "Carefully read these Terms of Service before ordering.",
        "Provide clear and detailed references: pose, colors, lighting, and other necessary details.",
        "Respond to messages and feedback requests in a timely manner.",
        "Missing or unclear information may cause delays or affect the final result.",
      ],
    },
    {
      roman: "IV",
      title: "Payment",
      items: [
        "PayPal only.",
        "Full payment is required upfront.",
        "Payment plans are available for commissions over $100.",
        "Prices may vary depending on the complexity of the request.",
        "Additional fees may apply if revision limits are exceeded.",
      ],
    },
    {
      roman: "V",
      title: "Refund policy",
      items: [
        "Full refund if the commission has not been started.",
        "During the sketch stage: 75% refund.",
        "No refund after the final sketch has been approved or once the final artwork has been completed.",
        "If I cannot finish the commission, 70% will be refunded, excluding transaction fees.",
        "Transaction fees are non-refundable. I am not responsible for mistakes made by the client during the transaction.",
      ],
    },
    {
      roman: "VI",
      title: "Revisions",
      items: [
        "You receive 3 free revisions total: 1 major during sketch and 2 minor during sketch/colors.",
        "Additional revisions may require extra fees depending on complexity.",
        "Major changes cannot be requested after coloring begins.",
        "Revisions caused by my mistakes are always free.",
        "No revisions after the artwork is completed.",
        "SKEB / Surprise Me commissions do not include revisions.",
      ],
    },
    {
      roman: "VII",
      title: "SKEB / Surprise Me",
      items: [
        "No previews or WIP updates will be provided.",
        "The final artwork will be a complete surprise.",
        "Pose and expression references are required.",
      ],
    },
    {
      roman: "VIII",
      title: "Workflow & delivery",
      items: [
        "Estimated completion time is 1–3 months. Bust-up and chibi commissions may take around 2 weeks.",
        "The ETA begins after the final sketch is approved.",
        "The process includes initial and final sketch, base colors, color sketch, and initial and final rendering.",
        "WIP updates will be provided at each stage for feedback. No progress will continue until each stage is approved.",
        "Sketches and WIPs will be shared via screenshots.",
        "Harassment regarding work speed will not be tolerated.",
      ],
    },
    {
      roman: "IX",
      title: "Copyright & usage",
      items: [
        "The Artist retains full copyright of the artwork, including portfolio display and streaming.",
        "The Client owns the character, but not the artwork itself.",
        "Allowed: personal printing, cropping/resizing, hue/saturation/brightness adjustments, and social posting with proper credit.",
        "Not allowed: claiming the artwork as your own, removing the watermark, unauthorized editing, NFTs/cryptocurrency/blockchain/generative AI use, or commercial use without purchased rights.",
      ],
    },
    {
      roman: "X",
      title: "Final delivery",
      items: [
        "The final artwork will be delivered as PNG files via Google Drive.",
        "Default size is 3300 × 4400px at 300–350 dpi. Request different sizes before work begins.",
        "A transparent background is available upon request before the lineart stage.",
        "Files remain available for up to 3 months. Please download and store them safely.",
      ],
    },
  ],
};
